/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacelanchonete;

import cadastro.Cadastro;
import cardapio.Acompanhamento;
import cardapio.AcompanhamentoLixo;
import cardapio.Lanche;
import classes.Mostrar;
import classes.Mostrar;
import classes.Pedido;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import metodos.Metodos;
import pessoas.Funcionario;

/**
 *
 * @author Pedro
 */
public class CadPedido extends javax.swing.JFrame {

    /**
     * Creates new form CadPedido
     */
    String cpf;
    String cpfCliente;
    String tipo;
    ArrayList<Pedido> pedidos = new ArrayList<>();
    public CadPedido(String cpf, String CpfCliente, String tipo) throws SQLException {
        this.cpfCliente = CpfCliente;
        this.cpf = cpf;
        this.tipo = tipo;
        initComponents();
        DefaultTableModel tabelaLanche = null;
        DefaultTableModel tabelaAcomp = null;
        Mostrar mostrar = new Mostrar();
        tabelaLanche = mostrar.mostrarLanche(tabelaL);
        tabelaAcomp = mostrar.mostraAcompanhamento(tabelaA);
        mostrarPedido();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaL = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaA = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaP = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_return_20px_2.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lanches", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tabelaL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Preço", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaL);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_add_20px.png"))); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acompanhamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tabelaA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Preço", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaA);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_add_20px.png"))); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pedido do Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tabelaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Qtd", "Tipo", "ID lanche/Acomp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaP);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_cancel_20px.png"))); // NOI18N
        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/icons8_add_20px.png"))); // NOI18N
        jButton5.setText("Cadastrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtCPF.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF do cliente"));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Metodos met = new Metodos();
        Funcionario f = met.busca(cpf);
        if(tipo.equals("cad")){
            if (f.getFuncao().equals("Vendedor")) {
                new MenuFuncionario(cpf).show();
            } else {
                new MenuGerente(cpf).show();
            }
        }else if(tipo.equals("entrega")){
            TelaEntrega entrega = new TelaEntrega(cpf);
            if(tabelaP.getRowCount() <= 0){
                JOptionPane.showMessageDialog(null, "VOCÊ NÃO EFETUOU O PEDIDO, EFETUE O PEDIDO");
                try {
                    new CadPedido(cpf,cpfCliente,tipo).show();
                } catch (SQLException ex) {
                    Logger.getLogger(CadPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                entrega.setVisible(true);
                this.dispose();
            }
        }else{
            AlterarPedido al = new AlterarPedido(cpf, cpfCliente);
            al.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void mostrarPedido() throws SQLException{
        if(!cpfCliente.equals("nada")){
            Pedido pedido = new Pedido();
            pedidos = pedido.buscarPedido(cpfCliente);
            DefaultTableModel tModel = (DefaultTableModel) tabelaP.getModel();
            tModel.setRowCount(pedidos.size());
            for (int i = 0; i < pedidos.size(); i++) {
                tabelaP.setValueAt(pedidos.get(i).getNome(), i, 0);
                tabelaP.setValueAt(pedidos.get(i).getPreco(), i, 1);
                tabelaP.setValueAt(pedidos.get(i).getQtd(), i, 2);
                tabelaP.setValueAt(pedidos.get(i).getTipo(), i, 3);
                tabelaP.setValueAt(pedidos.get(i).getID_lanche_Acomp(), i, 4);
            }
            txtCPF.setText(cpfCliente);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel origem = (DefaultTableModel)tabelaL.getModel();
       DefaultTableModel destino = (DefaultTableModel)tabelaP.getModel();
       String qtdPedido = "";
       qtdPedido = JOptionPane.showInputDialog(this, qtdPedido);
       try{
            int qtdEstoque=(int)origem.getValueAt(tabelaL.getSelectedRow(), 3);

            int codigo= (int)origem.getValueAt(tabelaL.getSelectedRow(), 0);

            int qtd = (int)origem.getValueAt(tabelaL.getSelectedRow(), 3);
            try{
             if(Integer.parseInt(qtdPedido)<=qtdEstoque){
                 int cont=0;
                 Object[] obj = {origem.getValueAt(tabelaL.getSelectedRow(), 1),origem.getValueAt(tabelaL.getSelectedRow(), 2),qtdPedido,"lanche",codigo};
                 if(buscar(destino,Integer.parseInt(String.valueOf(origem.getValueAt(tabelaL.getSelectedRow(), 0))), "lanche")){
                     for(int i=0; i<destino.getRowCount(); i++){
                         String nomeD = String.valueOf(destino.getValueAt(i, 0));
                         if(nomeD.equals(String.valueOf(tabelaL.getValueAt(tabelaL.getSelectedRow(), 1)))){
                             destino.setValueAt(Integer.parseInt(qtdPedido)+Integer.parseInt(String.valueOf(destino.getValueAt(i, 2))), i, 2);
                             cont++;
                         }
                     }
                 }
                 if(qtdEstoque-Integer.parseInt(qtdPedido)==0){
                      origem.removeRow(tabelaL.getSelectedRow());
                 }else{
                     qtd = qtd - Integer.parseInt(qtdPedido);
                     origem.setValueAt(qtd,tabelaL.getSelectedRow(),3);
                 }

                 if(cont==0){
                     destino.addRow(obj);
                 }
             }else{
                 JOptionPane.showMessageDialog(this, "Quantidade insuficiente");
             }
            }catch(NumberFormatException ne){}
       }catch(ArrayIndexOutOfBoundsException ae){}
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean buscar(DefaultTableModel destino,int codigo, String tipo){
        int qtdLinha = destino.getRowCount();
        for(int i=0; i<qtdLinha; i++){
            if(codigo==Integer.parseInt(String.valueOf(destino.getValueAt(i, 4))) && tipo.equals("lanche")){
                return true;
            }else if(codigo==(int)destino.getValueAt(i, 4) && tipo.equals("acomp")){
                return true;
            }
        }
        return false;
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel origem = (DefaultTableModel)tabelaA.getModel();
       DefaultTableModel destino = (DefaultTableModel)tabelaP.getModel();
       String qtdPedido = "";
       qtdPedido = JOptionPane.showInputDialog(this, qtdPedido);
       int qtdEstoque=(int)origem.getValueAt(tabelaA.getSelectedRow(), 3);
       
       int codigo= (int)origem.getValueAt(tabelaA.getSelectedRow(), 0);
       
       int qtd = (int)origem.getValueAt(tabelaA.getSelectedRow(), 3);
       
       if(Integer.parseInt(qtdPedido)<=qtdEstoque){
           int cont=0;
           Object[] obj = {origem.getValueAt(tabelaA.getSelectedRow(), 1),origem.getValueAt(tabelaA.getSelectedRow(), 2),qtdPedido,"acomp",codigo};
           if(buscar(destino,Integer.parseInt(String.valueOf(origem.getValueAt(tabelaA.getSelectedRow(), 0))), "lanche")){
               for(int i=0; i<destino.getRowCount(); i++){
                   String nomeD = String.valueOf(destino.getValueAt(i, 0));
                   if(nomeD.equals(String.valueOf(tabelaA.getValueAt(tabelaA.getSelectedRow(), 1)))){
                       destino.setValueAt(Integer.parseInt(qtdPedido)+Integer.parseInt(String.valueOf(destino.getValueAt(i, 2))), i, 2);
                       cont++;
                   }
               }
           }
           if(qtdEstoque-Integer.parseInt(qtdPedido)==0){
                origem.removeRow(tabelaA.getSelectedRow());
           }else{
               qtd = qtd - Integer.parseInt(qtdPedido);
               origem.setValueAt(qtd,tabelaA.getSelectedRow(),3);
           }
           
           if(cont==0){
               destino.addRow(obj);
           }
       }else{
           JOptionPane.showMessageDialog(this, "Quantidade insuficiente");
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel table = (DefaultTableModel)tabelaP.getModel();
        DefaultTableModel origem = (DefaultTableModel)tabelaL.getModel();
        if(table.getValueAt(tabelaP.getSelectedRow(), 4).equals("lanche")){
            int qtd = Integer.parseInt(String.valueOf(table.getValueAt(tabelaP.getSelectedRow(), 3)));
            int codigo = Integer.parseInt(String.valueOf(table.getValueAt(tabelaP.getSelectedRow(), 0)));
            int qtdLinhas = tabelaL.getModel().getRowCount();
            for(int i=0; i<qtdLinhas; i++){
                if(Integer.parseInt(String.valueOf(origem.getValueAt(i, 0)))==codigo){
                    origem.setValueAt(qtd+Integer.parseInt(String.valueOf(tabelaL.getValueAt(tabelaL.getSelectedRow(), 3))), i, 3);
                }
            }
        }
        table.removeRow(tabelaP.getSelectedRow());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int qtdLinhas = tabelaP.getModel().getRowCount();
        if(tipo.equals("cad")){
            for(int i=0; i<qtdLinhas; i++){
                Pedido pedido = new Pedido();
                pedido.setCpf(txtCPF.getText());
                pedido.setNome(String.valueOf(tabelaP.getValueAt(i, 0)));
                pedido.setPreco(Double.parseDouble(String.valueOf(tabelaP.getValueAt(i, 1))));
                pedido.setQtd(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 2))));
                pedido.setTipo(String.valueOf(tabelaP.getValueAt(i, 3)));
                pedido.setID_lanche_Acomp(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                Cadastro cad = new Cadastro();
                if(pedido.getTipo().equals("lanche")){
                    Lanche lanche = new Lanche();
                    lanche = lanche.buscarLanche(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                    if(lanche.getQtd()>pedido.getQtd()){
                        lanche.setQtd(lanche.getQtd()-pedido.getQtd());
                    }
                    cad.alterarLanche(lanche);
                }else if(pedido.getTipo().equals("acomp")){
                    Acompanhamento acomp = new Acompanhamento();
                    acomp = acomp.buscarAcomp(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                    if(acomp.getQtd()>pedido.getQtd()){
                        acomp.setQtd(acomp.getQtd()-pedido.getQtd());
                    }
                    cad.alterarAcomp(acomp);
                }
                cad.cadastrarPedido(pedido);
            }
            JOptionPane.showMessageDialog(null, "pedido Cadastrado com sucesso!");
        }else if(tipo.equals("altera")){
            Cadastro cad2 = new Cadastro();
            cad2.removerPedido(cpfCliente);
            for(int i=0; i<qtdLinhas; i++){
                Pedido pedido = new Pedido();
                pedido.setCpf(cpfCliente);
                pedido.setNome(String.valueOf(tabelaP.getValueAt(i, 0)));
                pedido.setPreco(Double.parseDouble(String.valueOf(tabelaP.getValueAt(i, 1))));
                pedido.setQtd(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 2))));
                pedido.setTipo(String.valueOf(tabelaP.getValueAt(i, 3)));
                pedido.setID_lanche_Acomp(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i,4))));
                Cadastro cad = new Cadastro();
                if(pedido.getTipo().equals("lanche")){
                    Lanche lanche = new Lanche();
                    lanche = lanche.buscarLanche(Integer.parseInt(String.valueOf(tabelaL.getValueAt(i, 0))));
                    if(lanche.getQtd()>pedido.getQtd()){
                        lanche.setQtd(lanche.getQtd()-pedido.getQtd());
                    }
                    cad.alterarLanche(lanche);
                }else if(pedido.getTipo().equals("acomp")){
                    Acompanhamento acomp = new Acompanhamento();
                    acomp = acomp.buscarAcomp(Integer.parseInt(String.valueOf(tabelaA.getValueAt(i, 0))));
                    if(acomp.getQtd()>pedido.getQtd()){
                        acomp.setQtd(acomp.getQtd()-pedido.getQtd());
                    }
                    cad.alterarAcomp(acomp);
                }
                cad.cadastrarPedido(pedido);
            }
            JOptionPane.showMessageDialog(null, "pedido Cadastrado com sucesso!");
        }else{
            for(int i=0; i<qtdLinhas; i++){
                Pedido pedido = new Pedido();
                pedido.setCpf(txtCPF.getText());
                pedido.setNome(String.valueOf(tabelaP.getValueAt(i, 0)));
                pedido.setPreco(Double.parseDouble(String.valueOf(tabelaP.getValueAt(i, 1))));
                pedido.setQtd(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 2))));
                pedido.setTipo(String.valueOf(tabelaP.getValueAt(i, 3)));
                pedido.setID_lanche_Acomp(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                Cadastro cad = new Cadastro();
                if(pedido.getTipo().equals("lanche")){
                    Lanche lanche = new Lanche();
                    lanche = lanche.buscarLanche(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                    if(lanche.getQtd()>pedido.getQtd()){
                        lanche.setQtd(lanche.getQtd()-pedido.getQtd());
                    }
                    cad.alterarLanche(lanche);
                }else if(pedido.getTipo().equals("acomp")){
                    Acompanhamento acomp = new Acompanhamento();
                    acomp = acomp.buscarAcomp(Integer.parseInt(String.valueOf(tabelaP.getValueAt(i, 4))));
                    if(acomp.getQtd()>pedido.getQtd()){
                        acomp.setQtd(acomp.getQtd()-pedido.getQtd());
                    }
                    cad.alterarAcomp(acomp);
                }
                cad.cadastrarPedido(pedido);
            }
            JOptionPane.showMessageDialog(null, "pedido Cadastrado com sucesso!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadPedido("","","").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CadPedido.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaA;
    private javax.swing.JTable tabelaL;
    private javax.swing.JTable tabelaP;
    private javax.swing.JFormattedTextField txtCPF;
    // End of variables declaration//GEN-END:variables
}
